# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false
org.gradle.configuration-cache=true

# Mod Properties
mod_id=usefulfoundation
mod_name=Useful Foundation
mod_license=MIT License
mod_version=1.0.0
mod_group_id=net.themcbrothers
mod_authors=TheMCBrothers
mod_description=It adds a lot of new materials and ores.

# Minecraft
minecraft_version=1.21
minecraft_version_range=[1.21,1.22)
minecraft_supported_versions=1.21,1.21.1

# NeoForge
neo_version=21.0.167
neo_version_range=[21,)
loader_version_range=[3,)

## Mappings
neoForge.parchment.minecraftVersion=1.21
neoForge.parchment.mappingsVersion=2024.07.07

# Dependencies
lib_version=1.21-8.0.0
lib_version_range=[1.21-8.0.0,)

# Publishing
archive_base=useful-foundation
artifact_type=release
github_repo=TheMCBrothers/Useful-Foundation
curse_project=355245
modrinth_project=jwQmhdWo
