modLoader = "javafml"
loaderVersion = "${loader_version_range}"
issueTrackerURL = "https://github.com/TheMCBrothers/Useful-Foundation/issues"
license = "MIT License"

[[mods]]
    modId = "usefulfoundation"
    version = "${file.jarVersion}"
    displayName = "Useful Foundation"
    updateJSONURL="https://forge.curseupdate.com/355245/usefulfoundation"
    displayURL = "https://themcbrothers.net/mods/usefulfoundation"
    logoFile="logo.png"
    logoBlur = false
    authors = "TheMCBrothers"
    description = '''
    This is a mod that adds new ores and materials
    '''

[[dependencies.usefulfoundation]]
    modId = "forge"
    mandatory = true
    versionRange = "${forge_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.usefulfoundation]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.usefulfoundation]]
    modId = "tmcb_lib"
    mandatory = true
    versionRange = "${themcbroslib_version_range}"
    ordering = "NONE"
    side = "BOTH"

[modproperties.usefulfoundation]
    catalogueItemIcon = "usefulfoundation:copper_gear"
