modLoader = "javafml" #mandatory
loaderVersion = "[47,)" #mandatory (46 is current forge version)
issueTrackerURL = "https://github.com/TheMCBrothers/Useful-Foundation/issues" #optional
license = "MIT License"

[[mods]] #mandatory
modId = "usefulfoundation" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Useful Foundation" #mandatory
# updateJSONURL="http://myurl.me/" #optional
displayURL = "https://themcbrothers.net/" #optional
# logoFile="examplemod.png" #optional
# credits="Thanks for this example mod goes to Java" #optional
authors = "TheMCBrothers" #optional
description = '''
This is a mod that adds new ores and materials
'''

[[dependencies.usefulfoundation]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[47,)" #mandatory
ordering = "NONE"
side = "BOTH"
# Here's another dependency
[[dependencies.usefulfoundation]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.usefulfoundation]]
modId = "tmcb_lib"
mandatory = true
versionRange = "[1.20.1-4.1.1,)"
ordering = "NONE"
side = "BOTH"
