@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package themcbros.usefulfoundation.init;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;