@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package themcbros.usefulfoundation.init;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;